apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dp
  labels:
    app: frontend-app
    type: frontend

spec:
  selector:
    matchLabels:
      type: frontend

  template:
    metadata:
      labels:
        app: frontend-pod
        type: frontend
    spec:
      containers:
      - name: nginx-container
        image: nginx
  replicas: 6
